# Cvxpy Layers Tutorial
For safe NNs

[Blog](https://locuslab.github.io/2019-10-28-cvxpylayers/)

[Paper](https://web.stanford.edu/~boyd/papers/pdf/diff_cvxpy.pdf)

[Applications in RL](https://dl.acm.org/doi/abs/10.1145/3447555.3464874)

In [28]:
import torch
from tqdm import tqdm
import os, sys
import numpy as np
import cvxpy as cp 
from cvxpylayers.torch import CvxpyLayer 

torch.manual_seed(42)
torch.set_printoptions(precision=4, sci_mode=False)


In [69]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.linear = torch.nn.Linear(2, 1, bias=False)
        #torch.nn.init.constant_(self.linear.weight, 2) 
    def forward(self, x):
        return self.linear(x)

In [70]:
X = torch.randn(5, 2) # n_batches, n_features
Y = X.detach().clone() @ torch.Tensor([[2],[2]])

In [74]:
net = Net()
opt = torch.optim.Adam( net.parameters(), lr=0.1)
list_l =[]

for i in range(100):
    opt.zero_grad()
    l = torch.nn.MSELoss()(net(X), Y)
    if i % 10 == 0:
        print(l.item())
    l.backward()
    opt.step()

print(net.linear.weight)

5.262478351593018
2.060473680496216
0.8606888651847839
0.2034994661808014
0.024738270789384842
0.0024578780867159367
0.006969773210585117
0.0049374583177268505
0.001099787768907845
1.1908976375707425e-05
Parameter containing:
tensor([[1.9908, 1.9866]], requires_grad=True)


In [75]:
torch.nn.MSELoss()(net(X), Y)

tensor(    0.0001, grad_fn=<MseLossBackward0>)

In [76]:
print(net(X))
print(Y)
print(torch.nn.MSELoss()(net(X), Y))

tensor([[ 2.1488],
        [-2.3810],
        [ 1.9026],
        [-1.8742],
        [ 1.6751]], grad_fn=<MmBackward0>)
tensor([[ 2.1527],
        [-2.3925],
        [ 1.9133],
        [-1.8798],
        [ 1.6862]])
tensor(    0.0001, grad_fn=<MseLossBackward0>)
